SUPPORTED_CONTENT_EXTS = {"docx", "xlsx", "pdf"}
MAX_DOCX_SIZE_MB = 30
MAX_XLSX_SIZE_MB = 30
MAX_PDF_SIZE_MB = 80
MAX_EXTRACTED_TEXT_CHARS = 2_000_000
MAX_PDF_OCR_PAGES = 30
PDF_EMBEDDED_SCORE_OK = 0.60
PDF_EMBEDDED_SCORE_BAD = 0.38
